<a href="https://colab.research.google.com/github/pedroUDF/ciencia_dados_maquina/blob/main/Cap2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python para Ciência de Dados**

* Manipulação de Dados Tabulares com Pandas - Funções Básicas

* Tipos de Dados com Pandas

* Renomeando Colunas

* Selecionando Linhas e Colunas

* Adicionando e Removendo Colunas

* Operações Básicas - Consultas

* Operações Básicas - Ordenação

* Operações Básicas - Combinando DataFrames

* Operações Básicas - Salvando DataFrames

In [3]:
import pandas as pd

In [4]:
cidades = pd.DataFrame(
    [
        ["Paraná", "Londrina", 575377, 1356.00],
        ["São Paulo", "São Carlos", 254484, 1508.00],
        ["Santa Catarina", "Florianópolis", 508826, 1798.00],
        ["Paraná", "Coritiba", 1223237, 1710.00],
        ["São Paulo", "Campinas", 1223237, 1710.00]
    ], columns=["Estado", "Cidade", "População", "Salário-Médio"]
)
cidades

           Estado         Cidade  População  Salário-Médio
0          Paraná       Londrina     575377         1356.0
1       São Paulo     São Carlos     254484         1508.0
2  Santa Catarina  Florianópolis     508826         1798.0
3          Paraná       Coritiba    1223237         1710.0
4       São Paulo       Campinas    1223237         1710.0

In [5]:
# Retorna um DataFrame com as n *primeiras* amostras.
cidades.head(2)

      Estado      Cidade  População  Salário-Médio
0     Paraná    Londrina     575377         1356.0
1  São Paulo  São Carlos     254484         1508.0

In [6]:
# Retorna um DataFrame com as n *ultimas* amostras.
cidades.tail(2)

      Estado    Cidade  População  Salário-Médio
3     Paraná  Coritiba    1223237         1710.0
4  São Paulo  Campinas    1223237         1710.0

In [7]:
# Mostra o número de linhas e colunas
cidades.shape

(5, 4)

In [8]:
# Imprimir informações gerais do dataframe
cidades.info

<bound method DataFrame.info of            Estado         Cidade  População  Salário-Médio
0          Paraná       Londrina     575377         1356.0
1       São Paulo     São Carlos     254484         1508.0
2  Santa Catarina  Florianópolis     508826         1798.0
3          Paraná       Coritiba    1223237         1710.0
4       São Paulo       Campinas    1223237         1710.0>

In [9]:
# Mostra uma lista de todas as colunas.
cidades.columns

Index(['Estado', 'Cidade', 'População', 'Salário-Médio'], dtype='object')

In [10]:
cidades["Salário-Médio"].describe()

count       5.000000
mean     1616.400000
std       180.318607
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1710.000000
max      1798.000000
Name: Salário-Médio, dtype: float64

In [11]:
cidades.dtypes
cidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   População      5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [12]:
cidades["População"] = cidades["População"].astype('float64')
cidades.dtypes

Estado            object
Cidade            object
População        float64
Salário-Médio    float64
dtype: object

In [13]:
cidades["Data"] = ["3-8-2021", "3-9-2021", "3-10-2021", "3-11-2021", "3-12-2021"]
# Setando a data para a forma que conhecemos (acho que nao funcionou nao kkk)
cidades["Data"] = pd.to_datetime(cidades["Data"], format='%d-%m-%Y')

cidades

           Estado         Cidade  População  Salário-Médio       Data
0          Paraná       Londrina   575377.0         1356.0 2021-08-03
1       São Paulo     São Carlos   254484.0         1508.0 2021-09-03
2  Santa Catarina  Florianópolis   508826.0         1798.0 2021-10-03
3          Paraná       Coritiba  1223237.0         1710.0 2021-11-03
4       São Paulo       Campinas  1223237.0         1710.0 2021-12-03

In [14]:
# Agora sim, seta a data no formato que conhecemos.
cidades["Data"] = cidades["Data"].dt.strftime('%d-%m-%Y') # Dia, Mês, Ano

cidades

           Estado         Cidade  População  Salário-Médio        Data
0          Paraná       Londrina   575377.0         1356.0  03-08-2021
1       São Paulo     São Carlos   254484.0         1508.0  03-09-2021
2  Santa Catarina  Florianópolis   508826.0         1798.0  03-10-2021
3          Paraná       Coritiba  1223237.0         1710.0  03-11-2021
4       São Paulo       Campinas  1223237.0         1710.0  03-12-2021

In [15]:
# Renomeando Colunas
cidades.rename(columns= {"População": "N° Habitantes", "Data": "Data - Censo"}, inplace=True) #inlpace=true serve para mudar na própria tabela, por padrão o rename cria uma cópia da tabela

cidades

           Estado         Cidade  N° Habitantes  Salário-Médio Data - Censo
0          Paraná       Londrina       575377.0         1356.0   03-08-2021
1       São Paulo     São Carlos       254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis       508826.0         1798.0   03-10-2021
3          Paraná       Coritiba      1223237.0         1710.0   03-11-2021
4       São Paulo       Campinas      1223237.0         1710.0   03-12-2021

In [16]:
# Selecionando colunas com os nomes especificados
cidadesHab = cidades[["N° Habitantes", "Salário-Médio"]]

cidadesHab

   N° Habitantes  Salário-Médio
0       575377.0         1356.0
1       254484.0         1508.0
2       508826.0         1798.0
3      1223237.0         1710.0
4      1223237.0         1710.0

In [17]:
#selecionando colunas, no exemplo, selecionei a 1 e a 3
cidades.loc[[1,3]]

      Estado      Cidade  N° Habitantes  Salário-Médio Data - Censo
1  São Paulo  São Carlos       254484.0         1508.0   03-09-2021
3     Paraná    Coritiba      1223237.0         1710.0   03-11-2021

In [18]:
# Fatiamento do Py - o último num não entra no fatiamento.
cidades.iloc[1:5]

           Estado         Cidade  N° Habitantes  Salário-Médio Data - Censo
1       São Paulo     São Carlos       254484.0         1508.0   03-09-2021
2  Santa Catarina  Florianópolis       508826.0         1798.0   03-10-2021
3          Paraná       Coritiba      1223237.0         1710.0   03-11-2021
4       São Paulo       Campinas      1223237.0         1710.0   03-12-2021

In [19]:
#  Seleciona todas as linhas e as duas primeiras colunas ( o ":" significa 'pegue tudo, selecione todas as linhas')
cidades.iloc[:, 0:2]

           Estado         Cidade
0          Paraná       Londrina
1       São Paulo     São Carlos
2  Santa Catarina  Florianópolis
3          Paraná       Coritiba
4       São Paulo       Campinas

In [20]:
# :3 == 0:3
cidades.iloc[:3, :3]

           Estado         Cidade  N° Habitantes
0          Paraná       Londrina       575377.0
1       São Paulo     São Carlos       254484.0
2  Santa Catarina  Florianópolis       508826.0

In [21]:
# Seleciona todas as linhas e as colunas determinadas
cidades.iloc[:, [1, 3, 0, 2]]

          Cidade  Salário-Médio          Estado  N° Habitantes
0       Londrina         1356.0          Paraná       575377.0
1     São Carlos         1508.0       São Paulo       254484.0
2  Florianópolis         1798.0  Santa Catarina       508826.0
3       Coritiba         1710.0          Paraná      1223237.0
4       Campinas         1710.0       São Paulo      1223237.0

In [22]:
# Estrutura do insert = df.insert(posição, "nome da coluna", ["valores"])
cidades.insert(2, "Sigla", ["PR", "SP", "SC", "PR", "SP"]) # Adiciona novos dados no índice dois
cidades.insert(2, "Sigla-Repetida", cidades["Sigla"]) # Adiciona uma coluna repetida "Sigla"

cidades

,Estado,Cidade,Sigla-Repetida,Sigla,N° Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,SC,508826.0,1798.0,03-10-2021
3,Paraná,Coritiba,PR,PR,1223237.0,1710.0,03-11-2021
4,São Paulo,Campinas,SP,SP,1223237.0,1710.0,03-12-2021

In [23]:
# Excluir coluna duplicada
cidades = cidades.drop(['Sigla-Repetida'], axis=1)
# ou cidades = cidades.pop("Sigla-Repetida")

cidades

,Estado,Cidade,Sigla,N° Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Coritiba,PR,1223237.0,1710.0,03-11-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

Diferença entre os códigos:

* **.pop** = exclui diretamente no *DataFrame* original

* **

* **.drop** = mais útil pois pode apagar várias colunas de uma vez

axis(0) = linha

axis(1) = coluna

 Para excluir diretamente no *DataFrame* original -> inplace=True.

 Para apagar multiplas colunas = .drop(['ColunaA', 'ColunaB'], axis=1)

In [24]:
# Consulta - df.query("nome coluna/linha + condição")
# As aspas são para evitar possíveis confusões, evitam o Py fazer a operação: Salário - Médio
cidades.query("`Salário-Médio` > 1400.0")

,Estado,Cidade,Sigla,N° Habitantes,Salário-Médio,Data - Censo
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Coritiba,PR,1223237.0,1710.0,03-11-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

In [25]:
# Pode se usar o "and" ou "or" para consultar mais de uma coisa ao mesmo tempo
cidades.query("`N° Habitantes` > 500000 and `N° Habitantes` < 1300000")

,Estado,Cidade,Sigla,N° Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
3,Paraná,Coritiba,PR,1223237.0,1710.0,03-11-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021

In [26]:
# Ordenação (sempre em ordem crescente)
cidades.sort_values(by="Cidade", inplace=True)

cidades

,Estado,Cidade,Sigla,N° Habitantes,Salário-Médio,Data - Censo
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021
3,Paraná,Coritiba,PR,1223237.0,1710.0,03-11-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021

In [27]:
cidades.sort_values(by="Salário-Médio", inplace=True)

cidades

,Estado,Cidade,Sigla,N° Habitantes,Salário-Médio,Data - Censo
0,Paraná,Londrina,PR,575377.0,1356.0,03-08-2021
1,São Paulo,São Carlos,SP,254484.0,1508.0,03-09-2021
3,Paraná,Coritiba,PR,1223237.0,1710.0,03-11-2021
4,São Paulo,Campinas,SP,1223237.0,1710.0,03-12-2021
2,Santa Catarina,Florianópolis,SC,508826.0,1798.0,03-10-2021

In [28]:
# Juntando Dataframes, mas agora, criando um
cidades_salarios = pd.DataFrame(
    [
        ["Paraná", "Londrina", 1356.00],
        ["São Paulo", "São Carlos", 1508.00],
        ["Santa Catarina", "Florianópolis", 1798.00],
        ["Paraná", "Curitiba", 2293.00],
        ["São Paulo", "Campinas", 1710.00]
    ], columns=["Estado", "Cidade", "Salário-Médio"])
cidades_salarios

           Estado         Cidade  Salário-Médio
0          Paraná       Londrina         1356.0
1       São Paulo     São Carlos         1508.0
2  Santa Catarina  Florianópolis         1798.0
3          Paraná       Curitiba         2293.0
4       São Paulo       Campinas         1710.0

In [29]:
# Criando mais uma tabela cidades_pop
cidades_pop = pd.DataFrame(
    [
        ["Londrina", 575377],
        ["São Carlos", 254484],
        ["Florianópolis", 508826],
        ["Curitiba", 1963726],
        ["Campinas", 1223237]
    ], columns=['Cidade', 'Habitantes'])
cidades_pop

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237

In [30]:
# Mesclando as tabelas
# on="Cidade" = Especifica qual coluna serve como chave de ligação
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade")

#Por padrão, o pd.merge só traz as linhas onde a cidade existe em ambas as tabelas

           Estado         Cidade  Salário-Médio  Habitantes
0          Paraná       Londrina         1356.0      575377
1       São Paulo     São Carlos         1508.0      254484
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Curitiba         2293.0     1963726
4       São Paulo       Campinas         1710.0     1223237

In [31]:
# how="outer" = Nenhuma linha é omitida, no anterior, tem um comando 'escondido' = how="inner"
pd.merge(left=cidades_salarios, right=cidades_pop, on="Cidade", how="outer")

           Estado         Cidade  Salário-Médio  Habitantes
0       São Paulo       Campinas         1710.0     1223237
1          Paraná       Curitiba         2293.0     1963726
2  Santa Catarina  Florianópolis         1798.0      508826
3          Paraná       Londrina         1356.0      575377
4       São Paulo     São Carlos         1508.0      254484

In [32]:
# Concatenação, parece com o anterior
cidades_df1 = pd.DataFrame(
    [
        ["Londrina", 575377],
        ["São Carlos", 254484],
        ["Florianópolis", 508826],
    ], columns=["Cidade", "Habitantes"])

cidades_df1

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826

In [33]:
cidades_df2 = pd.DataFrame(
    [
        ["Curitiba", 1963726],
        ["Campinas", 1223237]
    ], columns=["Cidade", "Habitantes"])

cidades_df2

     Cidade  Habitantes
0  Curitiba     1963726
1  Campinas     1223237

In [34]:
pd.concat([cidades_df1, cidades_df2], ignore_index=True)
# ignore_index =True: Refaz a contagem numérica das linhas (os índices) do zero (0, 1, 2, 3, 4).

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237