<a href="https://colab.research.google.com/github/pedroUDF/ciencia_dados_maquina/blob/main/Capitulo2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python para Ciência de Dados**

* Manipulação de Dados Tabulares com Pandas - Funções Básicas

* Tipos de Dados com Pandas

* Renomeando Colunas

* Selecionando Linhas e Colunas

* Adicionando e Removendo Colunas

* Operações Básicas - Consultas

* Operações Básicas - Ordenação

* Operações Básicas - Combinando DataFrames

* Operações Básicas - Salvando DataFrames

In [3]:
import pandas as pd

In [4]:
cidades = pd.DataFrame(
    [
        ["Paraná", "Londrina", 575377, 1356.00],
        ["São Paulo", "São Carlos", 254484, 1508.00],
        ["Santa Catarina", "Florianópolis", 508826, 1798.00],
        ["Paraná", "Coritiba", 1223237, 1710.00],
        ["São Paulo", "Campinas", 1223237, 1710.00]
    ], columns=["Estado", "Cidade", "População", "Salário-Médio"]
)
cidades

           Estado         Cidade  População  Salário-Médio
0          Paraná       Londrina     575377         1356.0
1       São Paulo     São Carlos     254484         1508.0
2  Santa Catarina  Florianópolis     508826         1798.0
3          Paraná       Coritiba    1223237         1710.0
4       São Paulo       Campinas    1223237         1710.0

In [5]:
#Retorna um DataFrame com as n *primeiras* amostras.
cidades.head(2)

      Estado      Cidade  População  Salário-Médio
0     Paraná    Londrina     575377         1356.0
1  São Paulo  São Carlos     254484         1508.0

In [ ]:
#Retorna um DataFrame com as n *ultimas* amostras.
cidades.tail(2)

      Estado    Cidade  População  Salário-Médio
3     Paraná  Coritiba    1223237         1710.0
4  São Paulo  Campinas    1223237         1710.0

In [ ]:
#Mostra o número de linhas e colunas
cidades.shape

(5, 4)

In [ ]:
#Imprimir informações gerais do dataframe
cidades.info

<bound method DataFrame.info of            Estado         Cidade  População  Salário-Médio
0          Paraná       Londrina     575377         1356.0
1       São Paulo     São Carlos     254484         1508.0
2  Santa Catarina  Florianópolis     508826         1798.0
3          Paraná       Coritiba    1223237         1710.0
4       São Paulo       Campinas    1223237         1710.0>

In [ ]:
#Mostra uma lista de todas as colunas.
cidades.columns

Index(['Estado', 'Cidade', 'População', 'Salário-Médio'], dtype='object')

In [6]:
cidades["Salário-Médio"].describe()

count       5.000000
mean     1616.400000
std       180.318607
min      1356.000000
25%      1508.000000
50%      1710.000000
75%      1710.000000
max      1798.000000
Name: Salário-Médio, dtype: float64

In [7]:
cidades.dtypes
cidades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Estado         5 non-null      object
 1   Cidade         5 non-null      object
 2   População      5 non-null      int64
 3   Salário-Médio  5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [8]:
cidades['Habitantes'] = cidades['Habitantes'].astype('float64')
cidades.dtypes

KeyError: 'Habitantes'